flowchart TD
  phenix[phenix<br/>layer 6<br/>workspaceRoot]
  phenix_de[phenix-de<br/>layer 5<br/>hostConsumer]
  phenix_hosts[phenix-hosts<br/>layer 5<br/>hostConsumer]
  phenix_nvim[phenix-nvim<br/>layer 2<br/>toolProvider]
  phenix_packages[phenix-packages<br/>layer 4<br/>packageProvider]
  phenix_pins[phenix-pins<br/>layer 0<br/>pins]
  phenix_tools[phenix-tools<br/>layer 2<br/>toolProvider]
  phenix --> phenix_de
  phenix --> phenix_hosts
  phenix --> phenix_nvim
  phenix --> phenix_packages
  phenix --> phenix_pins
  phenix --> phenix_tools
  phenix_de --> phenix_pins
  phenix_hosts --> phenix_pins
  phenix_nvim --> phenix_pins
  phenix_packages --> phenix_pins
  phenix_tools --> phenix_pins

